apis:
  demonstration:
    root: index.yaml
  sts:
    root: oauth2/sts/index.yaml
  stsWithRAA:
    root: oauth2/stsWithRAA/index.yaml
lint:
  extends:
    - all
  rules:
    path-segment-plural: off
    request-mime-type:
      severity: error
      allowedValues:
        - application/json
        - text/html
        - application/pdf
