apis:
  demonstration:
    root: index.yaml
  sts:
    root: oauth2/sts/index.yaml
  stsWithRAA:
    root: oauth2/stsWithRAA/index.yaml
extends:
  - all
rules:
  path-segment-plural: off
  request-mime-type:
    severity: error
    allowedValues:
      - application/json
      - text/html
      - application/pdf
      - application/x-www-form-urlencoded
  # `parameter-description` is currently too strict. A perfectly good description inherited from the schema, and shown
  # in the HTML, is not counted as a description.
  parameter-description: off
  # TODO off for now, but should be enabled; needs fixes here
  operation-4xx-problem-details-rfc7807: off
  tags-alphabetical: off
  spec-strict-refs: off
  # Disabled because joi-to-json does not want to add a minLength for enums or strings with a pattern
  required-string-property-missing-min-length: off
  # Disabled because conflicting name "schema" could not be resolved
  # It should be possible to only disable this for schemas, but that doesn't seem to work
  component-name-unique: off
