# Copyright 2020 - 2021 PeopleWare n.v.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

openapi: 3.0.3
info:
  title: ppwcode openapi demonstration
  description: >-
    Collection of common OpenAPI 3 specs
  version: 0.0.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: PeopleWare n.v.
    email: info@peopleware.be
    url: 'https://www.peopleware.be/'
servers:
  - url: 'https://www.ppwcode.org/openapi/common'
    description: Dummy endpoint. There is nothing here.
paths:
  /demonstration:
    parameters:
      - $ref: 'parameters/forceError.yaml'
      - $ref: 'parameters/flowId.yaml'
      - $ref: 'parameters/mode.yaml'
      - $ref: 'oauth2/authorization.yaml'
      - $ref: 'parameters/at.yaml'
    get:
      summary: Demonstration of common specs for `GET`
      description: Every common spec is mentioned here.
      operationId: demonstrationGet
      responses:
        '200':
          x-summary: The resource exists
          description: Every common spec is mentioned here.  The `200` response shows `readOnly` properties.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resource'
        '401':
          $ref: 'oauth2/401.yaml'
        '403':
          $ref: 'oauth2/403.yaml'
    put:
      summary: Demonstration of common specs for `PUT`
      description: Every common spec is mentioned here. The request body does not show `readOnly` properties.
      operationId: demonstrationPut
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/resource'
      responses:
        '200':
          x-summary: The resource was updated
          description: Every common spec is mentioned here.  The `200` response shows `readOnly` properties.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resource'
        '401':
          $ref: 'oauth2/401.yaml'
        '403':
          $ref: 'oauth2/403.yaml'
components:
  schemas:
    resource:
      allOf:
        - $ref: 'resource/Audited.yaml'
        - type: object
          properties:
            human:
              type: object
              properties:
                gender:
                  $ref: 'human/Gender.yaml'
            id:
              type: object
              properties:
                naturalPerson:
                  type: object
                  properties:
                    be:
                      type: object
                      properties:
                        inss:
                          $ref: 'id/naturalPerson/be/INSS.yaml'
                uuid:
                  $ref: 'id/UUID.yaml'
            location:
              type: object
              properties:
                address:
                  $ref: 'location/Address.yaml'
                country:
                  $ref: 'location/Country.yaml'
            oauth2:
              type: object
              properties:
                bearerAccessToken:
                  $ref: 'oauth2/BearerAccessToken.yaml'
                errorResponse:
                  $ref: 'oauth2/ErrorResponse.yaml'
                wwwAuthenticate:
                  $ref: 'oauth2/WWWAuthenticate.yaml'
            resource:
              type: object
              properties:
                audited:
                  $ref: 'resource/Audited.yaml'
                versioned:
                  $ref: 'resource/Versioned.yaml'
            string:
              type: object
              properties:
                language:
                  $ref: 'string/Language.yaml'
                telephoneNumber:
                  $ref: 'string/TelephoneNumber.yaml'
                trimmedString:
                  $ref: 'string/TrimmedString.yaml'
            time:
              type: object
              properties:
                dateTime:
                  $ref: 'time/DateTime.yaml'
                changeDateTime:
                  $ref: 'time/ChangeDateTime.yaml'
                dayDate:
                  $ref: 'time/DayDate.yaml'
                dayDateInterval:
                  $ref: 'time/DayDateInterval.yaml'
