# Copyright 2021 - 2021 PeopleWare n.v.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

openapi: 3.0.3
info:
  title: ppwcode STS
  description: >-
    Spec for an OAuth2 Secure Token Service (STS), according to [RFC 6749](https://tools.ietf.org/html/rfc6749).

    To learn about OAuth2, we found ["OAuth 2.0 Simplified" by Aaron Parecki](https://www.oauth.com/) to be a very good
    resource.
  version: 1.0.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: PeopleWare n.v.
    email: info@peopleware.be
    url: 'https://www.peopleware.be/'
servers:
  - url: 'https://www.ppwcode.org/openapi/common/sts'
    description: Dummy endpoint. There is nothing here.
paths:
  /token:
    $ref: 'token/resource.yaml'
  '/.well-known/jwks.json':
    $ref: 'JWKS/JWKSResource.yaml'
  /jwt:
    $ref: 'JWT/RegisteredJWTClaimSetResource.yaml'
components:
  schemas:
    # Token requests bodies listed explicitly here as workaround for https://github.com/Redocly/redoc/issues/862#issuecomment-491631228
    # This is actually used in `TokenRequestBody.yaml`.
    authorization_code:
      $ref: 'token/request/AuthorizationCodeTokenRequestBody.yaml'
    client_credentials:
      $ref: 'token/request/ClientCredentialsTokenRequestBody.yaml'
    refresh_token:
      $ref: 'token/request/RefreshTokenTokenRequestBody.yaml'
    RSA:
      $ref: 'JWKS/RSAJWK.yaml'
    EC:
      $ref: 'JWKS/ECJWK.yaml'
